name: CI

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '10', '12', '14' ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: volta-cli/action@v1
      with:
        node-version: ${{ matrix.node-version }}
        yarn-version: 1.22.10

    - run: yarn install
    - run: yarn lint
    - run: yarn typecheck
    - run: yarn test
